version = 0.1
[default.deploy.parameters]
stack_name = "simple-dynamodb"
resolve_s3 = true
s3_prefix = "simple-dynamodb"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
